import type { Manager } from "../core/context";
export const DEFAULTS = {
  projectName: "next-skeleton-app",
  router: "app",
  github: { enabled: true, visibility: "private" },
  manager: "pnpm" as Manager,
  install: true,
  shadcn: {
    enabled: true as const,
    components: [
      "button",
      "input",
      "dialog",
      "card",
      "dropdown-menu",
      "form",
      "label",
      "select",
      "textarea",
      "accordion",
      "alert",
      "avatar",
      "badge",
      "breadcrumb",
      "checkbox",
      "separator",
      "tooltip",
    ],
  },
} as const;
